In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import pandas as pd

In [11]:
df=pd.read_csv('loan_approval_dataset.csv')
df

,Age,Salary,Credit_Score,Loan_Amount,Loan_Term,Employment_Status,Residence_Type,Previous_Default,Loan_Approved
0,56,136748,584,38209,36 months,Employed,Owned,Yes,Yes
1,46,25287,815,27424,24 months,Self-Employed,Rented,No,Yes
2,32,146593,398,42396,12 months,Unemployed,Rented,Yes,Yes
3,60,54387,696,11370,24 months,Unemployed,Owned,No,No
4,25,28512,788,14528,12 months,Employed,Owned,No,No
...,...,...,...,...,...,...,...,...,...
995,22,49241,500,41020,24 months,Self-Employed,Owned,No,Yes
996,40,116214,423,12415,48 months,Self-Employed,Owned,No,Yes
997,27,64569,300,28155,36 months,Self-Employed,Rented,Yes,Yes
998,61,31745,490,48884,12 months,Self-Employed,Mortgage,No,Yes
999,19,46029,815,21964,24 months,Employed,Mortgage,Yes,No

In [14]:
df.corr(numeric_only=True)

                   Age    Salary  Credit_Score  Loan_Amount
Age           1.000000  0.060125     -0.018835    -0.000500
Salary        0.060125  1.000000     -0.011185    -0.000635
Credit_Score -0.018835 -0.011185      1.000000     0.008741
Loan_Amount  -0.000500 -0.000635      0.008741     1.000000

In [12]:
model=LogisticRegression()

'''parameters'''

'''1) penalty : ['l1', 'l2', 'elasticnet']'''
# model=LogisticRegression(penalty='l1)       
# model=LogisticRegression(penalty='l2)           ( default penalty is l2)
# model=LogisticRegression(penalty='l3)

'''2) solver : ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']]'''
# It is an optimization engine which helps the gradient descent to find best weights.
# except liblinear every solver supports multinomial class labels.
# sag and saga we use when we have multiple features for fast convergence.

# solver	                        l1_ratio	                  multinomial multiclass
# 'lbfgs'                        	'l1',None                             yes                      [In l1_ratio "none" means use gradient descent]
# 'liblinear'	                    'l1','l2'	                          no
# 'newton-cg'	                    'l2',None                             yes
# 'newton-cholesky'               	'l2',None                             yes
# 'sag'                         	'l2',None                          	  yes
# 'saga'	                        'l1','l2','elasticNet', None          yes

'''3) max_iter  '''
# maximum no.of iterations taken for the solver to find best weights
# max_iter : Int = 100,          (default 100, we can change the value if the it not find the best weight)
#

'''4) class_weight'''
# class_weight = None | 'balnced'
#              resampling

'''5) c:'''
# It is an regularization strength. It decides the model is going to be underfit(becoz of not strict) or  overfit(becoz of too strict) or goodfit.

'5) c:'

In [13]:
model=LogisticRegression()